[settings]
dotfiles.root = "{{ pwd }}"
dotfiles.default_mode = "symlink-each"

[dotfiles]
"~" = { source = "", exclude = [
    "mise.toml",
    "*.md",
    ".git",
    ".gitignore",
    "Makefile",
    "node_modules",
    "package-lock.json"
] }
