[tools]
fastfetch = "latest"
gdu = "latest"
usage = "latest"
witr = "latest"
yazi = "latest"

[bootstrap.hooks.final]
run = [
    "if type node > /dev/null 2>&1; then node ~/.help/mise/populate_path.js; else mise x node -- node ~/.help/mise/populate_path.js; fi",
    "bash ~/.startup.sh"
]